DELETE FROM ASSIGNMENT_GRADIENTS;
DELETE FROM ASSIGNMENTS;
DELETE FROM RUN_SUMMARY;
DELETE FROM JOBS;
DELETE FROM RUNS;
DELETE FROM VEHICLES;
DELETE FROM EMISSION_FACTORS;
DELETE FROM SETTINGS;
DELETE FROM CONGESTION_INDEX;

-- #######################################################
-- 1. 초기 데이터 INSERT (DML) - 수정된 DDL에 맞춤
-- #######################################################

-- 1. EMISSION_FACTORS (배출 계수 마스터) 데이터
INSERT INTO EMISSION_FACTORS(VEHICLE_TYPE, FUEL_TYPE, CO2_GPKM, IDLE_GPS, NOTE)
VALUES('25톤 트랙터', '경유', 1250.5, 11.2, '컨테이너 트랙터 표준 배출계수 (2024년 기준 가상값)');

-- 2. VEHICLES (차량 마스터) 데이터
INSERT INTO VEHICLES (VEHICLE_ID, FACTOR_ID, VEHICLE_TYPE, MODEL_NAME, CAPACITY_KG) VALUES
('부산82가1234', (SELECT FACTOR_ID FROM EMISSION_FACTORS WHERE VEHICLE_TYPE = '25톤 트랙터'), 'TRACTOR', '현대 엑시언트', 25000.00);
INSERT INTO VEHICLES (VEHICLE_ID, FACTOR_ID, VEHICLE_TYPE, MODEL_NAME, CAPACITY_KG) VALUES
('인천88사5678', (SELECT FACTOR_ID FROM EMISSION_FACTORS WHERE VEHICLE_TYPE = '25톤 트랙터'), 'TRACTOR', '볼보 FH16', 25000.00);

-- 3. RUNS (최적화 실행 요청) 데이터
-- 시나리오: 군산 CY에서 출발하여 부산신항으로 가는 단일 운송 요청
INSERT INTO RUNS (RUN_ID, RUN_DATE, DEPOT_LAT, DEPOT_LON, OPTIMIZATION_STATUS, NATURAL_LANGUAGE_INPUT) VALUES
('RUN_20251015_001', TO_DATE('2025-10-15', 'YYYY-MM-DD'), 35.940000, 126.680000, 'COMPLETED', '군산 CY에서 출발해서 부산신항에 컨테이너 1개 운송');

-- 4. JOBS (배송 작업 상세) 데이터
-- 목적지: 부산신항 (ID: 1이 할당된다고 가정)
INSERT INTO JOBS (RUN_ID, SECTOR_ID, ADDRESS, LATITUDE, LONGITUDE, DEMAND_KG) VALUES
('RUN_20251015_001', 'BUSAN_NEW_PORT', '부산광역시 강서구 신항남로 367', 35.0931, 128.8239, 22000.00);

-- 5. RUN_SUMMARY (결과 요약) 데이터
INSERT INTO RUN_SUMMARY (RUN_ID, ROUTE_OPTION_NAME, TOTAL_DISTANCE_KM, TOTAL_CO2_G, TOTAL_TIME_MIN, LLM_EXPLANATION) VALUES
('RUN_20251015_001', '네이버 추천 경로', 290.1, 362770.05, 220, '통행량이 적고 운전이 편한 경로입니다.');
INSERT INTO RUN_SUMMARY (RUN_ID, ROUTE_OPTION_NAME, TOTAL_DISTANCE_KM, TOTAL_CO2_G, TOTAL_TIME_MIN, LLM_EXPLANATION) VALUES
('RUN_20251015_001', '카카오 최단 경로', 285.5, 357015.25, 215, '거리가 가장 짧은 경로입니다.');

-- 6. ASSIGNMENTS (경로 노드 및 배차 상세) 데이터
-- (핵심) LOAD_KG와 AVG_GRADIENT_PCT 컬럼 추가
-- '네이버 추천 경로'에 대한 스텝
INSERT INTO ASSIGNMENTS (RUN_ID, ROUTE_OPTION_NAME, VEHICLE_ID, STEP_ORDER, START_JOB_ID, END_JOB_ID, DISTANCE_KM, CO2_G, LOAD_KG, TIME_MIN, AVG_GRADIENT_PCT, CONGESTION_FACTOR) VALUES
('RUN_20251015_001', '네이버 추천 경로', '부산82가1234', 1, NULL, 1, 290.1, 362770.05, 22000.00, 220, 0.50, 1.1); -- LOAD_KG: 22000.00, AVG_GRADIENT_PCT: 0.50

-- '카카오 최단 경로'에 대한 스텝
INSERT INTO ASSIGNMENTS (RUN_ID, ROUTE_OPTION_NAME, VEHICLE_ID, STEP_ORDER, START_JOB_ID, END_JOB_ID, DISTANCE_KM, CO2_G, LOAD_KG, TIME_MIN, AVG_GRADIENT_PCT, CONGESTION_FACTOR) VALUES
('RUN_20251015_001', '카카오 최단 경로', '부산82가1234', 1, NULL, 1, 285.5, 357015.25, 22000.00, 215, 0.30, 1.12); -- LOAD_KG: 22000.00, AVG_GRADIENT_PCT: 0.30

-- 7. ASSIGNMENT_GRADIENTS (경로 스텝별 경사도 구간 상세 정보)
-- DDL은 유지하지만, co2_calculator.py가 이 데이터를 사용하지 않으므로 DML은 비워둡니다.

-- #######################################################
-- 2. SETTINGS (가중치/상수) 초기화
-- #######################################################
-- co2_calculator.py에서 사용하는 beta_grade 항목 포함
MERGE INTO SETTINGS s USING dual ON (s.key = 'alpha_load')
WHEN NOT MATCHED THEN INSERT (key, value) VALUES ('alpha_load','0.10');

MERGE INTO SETTINGS s USING dual ON (s.key = 'beta_grade')
WHEN NOT MATCHED THEN INSERT (key, value) VALUES ('beta_grade','0.03');

MERGE INTO SETTINGS s USING dual ON (s.key = 'speed_idle_threshold')
WHEN NOT MATCHED THEN INSERT (key, value) VALUES ('speed_idle_threshold','15');

MERGE INTO SETTINGS s USING dual ON (s.key = 'grade_cap')
WHEN NOT MATCHED THEN INSERT (key, value) VALUES ('grade_cap','0.30');

-- #######################################################
-- 3. CONGESTION_INDEX 초기 데이터 주입
-- #######################################################
INSERT INTO CONGESTION_INDEX (COMPUTED_AT, HOUR_OF_DAY, TIME_FACTOR, IDLE_FACTOR) VALUES
(SYSTIMESTAMP, 8, 1.30, 0.10); -- 오전 8시: 시간 30% 가중, 공회전 10% 가중
INSERT INTO CONGESTION_INDEX (COMPUTED_AT, HOUR_OF_DAY, TIME_FACTOR, IDLE_FACTOR) VALUES
(SYSTIMESTAMP, 18, 1.35, 0.12); -- 오후 6시: 시간 35% 가중, 공회전 12% 가중

COMMIT;

ALTER TABLE RUN_SUMMARY MODIFY (TOTAL_CO2_G NUMBER(12,3));
ALTER TABLE ASSIGNMENTS MODIFY (CO2_G NUMBER(12,5));