-- ===============================
-- ITS / WEATHER 초기 데이터 DML
-- (스키마: sql/oracle_ddl_complete.sql 기준)
-- ===============================

-- 존재 데이터 삭제 (해당 테이블만)
DELETE FROM ITS_TRAFFIC;
DELETE FROM WEATHER_FORECAST;

-- ITS_TRAFFIC: CSV 헤더 매핑
--   linkId, roadName, speed_kmh, congestion_level, observed_at
INSERT INTO ITS_TRAFFIC (LINK_ID, ROAD_NAME, SPEED_KMH, CONGESTION_LEVEL, OBSERVED_AT)
VALUES ('110000123', '서해안고속도로', 72.5, 'M', TO_TIMESTAMP('2025-10-15 08:10', 'YYYY-MM-DD HH24:MI'));

INSERT INTO ITS_TRAFFIC (LINK_ID, ROAD_NAME, SPEED_KMH, CONGESTION_LEVEL, OBSERVED_AT)
VALUES ('110000124', '서해안고속도로', 58.2, 'H', TO_TIMESTAMP('2025-10-15 18:05', 'YYYY-MM-DD HH24:MI'));

-- WEATHER_FORECAST: CSV 헤더 매핑
--   baseDate, baseTime, category, fcstDate, fcstTime, fcstValue, nx, ny
INSERT INTO WEATHER_FORECAST (BASE_DATE, BASE_TIME, CATEGORY, FCST_DATE, FCST_TIME, FCST_VALUE, NX, NY)
VALUES ('20251015', '0800', 'T1H', '20251015', '0900', '16', 55, 68);

INSERT INTO WEATHER_FORECAST (BASE_DATE, BASE_TIME, CATEGORY, FCST_DATE, FCST_TIME, FCST_VALUE, NX, NY)
VALUES ('20251015', '0800', 'RN1', '20251015', '0900', '0', 55, 68);

COMMIT;


