-- WEATHER 실황/예보 (격자 기반)
CREATE TABLE WEATHER_OBS (
  ID NUMBER PRIMARY KEY,
  BASE_TS TIMESTAMP NOT NULL,     -- 기준시각(KST)
  NX NUMBER(6,0) NOT NULL,        -- 격자 X
  NY NUMBER(6,0) NOT NULL,        -- 격자 Y
  T1H NUMBER(6,2),                -- 기온(℃)
  RN1 NUMBER(6,2),                -- 1시간 강수량(mm)
  UUU NUMBER(8,2), VVV NUMBER(8,2), -- 풍속 성분(m/s) (필드명은 가변)
  REH NUMBER(6,2),                -- 습도(%)
  PTY NUMBER(2,0),                -- 강수형태 코드
  INGESTED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE WEATHER_OBS_SEQ START WITH 1;
CREATE OR REPLACE TRIGGER WEATHER_OBS_TRG
BEFORE INSERT ON WEATHER_OBS FOR EACH ROW
BEGIN IF :NEW.ID IS NULL THEN :NEW.ID := WEATHER_OBS_SEQ.NEXTVAL; END IF; END;
/

-- ITS 링크 속도/교통량
CREATE TABLE ITS_TRAFFIC (
  ID NUMBER PRIMARY KEY,
  LINK_ID VARCHAR2(40) NOT NULL,
  OBS_TS TIMESTAMP NOT NULL,
  SPEED_KMH NUMBER(6,2),
  VOLUME NUMBER(10),
  OCCUPANCY NUMBER(6,2),
  INGESTED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE ITS_TRAFFIC_SEQ START WITH 1;
CREATE OR REPLACE TRIGGER ITS_TRAFFIC_TRG
BEFORE INSERT ON ITS_TRAFFIC FOR EACH ROW
BEGIN IF :NEW.ID IS NULL THEN :NEW.ID := ITS_TRAFFIC_SEQ.NEXTVAL; END IF; END;
/

-- 도로 종단선형(경사도)
CREATE TABLE ROAD_GRADES (
  SECTION_ID NUMBER PRIMARY KEY,
  ROUTE_ID VARCHAR2(40) NOT NULL,
  START_KM NUMBER(10,3) NOT NULL,
  END_KM NUMBER(10,3) NOT NULL,
  GRADE_PCT NUMBER(6,3),
  START_LAT NUMBER(10,6),
  START_LON NUMBER(10,6),
  END_LAT NUMBER(10,6),
  END_LON NUMBER(10,6),
  INGESTED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE ROAD_GRADES_SEQ START WITH 1;
CREATE OR REPLACE TRIGGER ROAD_GRADES_TRG
BEFORE INSERT ON ROAD_GRADES FOR EACH ROW
BEGIN IF :NEW.SECTION_ID IS NULL THEN :NEW.SECTION_ID := ROAD_GRADES_SEQ.NEXTVAL; END IF; END;
/

-- 차종별 배출계수 (주행/공회전)
CREATE TABLE VEHICLE_EMISSION_FACTORS (
  ID NUMBER PRIMARY KEY,
  VEHICLE_CLASS VARCHAR2(30) NOT NULL,  -- e.g., '25T_CARGO' / 'TRACTOR'
  CO2_GPKM NUMBER(10,2) NOT NULL,       -- g/km
  IDLE_CO2_GPM NUMBER(10,2),            -- g/min
  SOURCE VARCHAR2(100),
  VERSION VARCHAR2(20),
  INGESTED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE SEQUENCE VEF_SEQ START WITH 1;
CREATE OR REPLACE TRIGGER VEF_TRG
BEFORE INSERT ON VEHICLE_EMISSION_FACTORS FOR EACH ROW
BEGIN IF :NEW.ID IS NULL THEN :NEW.ID := VEF_SEQ.NEXTVAL; END IF; END;
/

-- 외부화된 설정값 (계수/가중치)
CREATE TABLE SETTINGS (
  KEY VARCHAR2(40) PRIMARY KEY,
  VALUE_NUM NUMBER(20,8),
  VALUE_TXT VARCHAR2(200),
  UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);
